# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main', 'feature-*']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.15.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - uses: actions/checkout@v4
        name: Checkout users
        with:
          path: arq-ii-weather-flow-users
      - uses: actions/checkout@v4
        name: Checkout weather
        if: ${{ github.event_name == 'push' }}
        with:
          repository: adriancardozo/arq-ii-weather-flow-weather
          ref: ${{ steps.branch.outputs.push_branch_name }}
          path: arq-ii-weather-flow-weather
      - uses: actions/checkout@v4
        name: Checkout arq-ii-weather-flow-weather
        if: ${{ github.event_name == 'pull_request' }}
        with:
          repository: adriancardozo/arq-ii-weather-flow-weather
          ref: ${{ steps.branch.outputs.pull_request_branch_name }}
          path: arq-ii-weather-flow-weather
      - run: docker compose -f 'arq-ii-weather-flow-users/docker-compose.e2e.yml' up -d
      - run: cd arq-ii-weather-flow-users && npm run test:e2e
